---

- name: Converge
  hosts: all
  pre_tasks:
    - name: update apt repository
      when: 'ansible_pkg_mgr == "apt"'
      apt:
        update_cache: true
  roles:
    - role: ansible-role-logstash
      vars:
        elk_logstash_plugins:
          - logstash-filter-fingerprint
