---

- name: establish man directory
  when: ansible_connection == 'docker'
  file:
    path: /usr/share/man/man1
    state: directory

- name: enable universe repository
  when: ansible_distribution == "Ubuntu"
  apt_repository:
    repo: "{{ item }}"
    update_cache: true
  loop:
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe"
    - "deb http://security.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security universe"

- name: update repos (docker)
  when:
    - ansible_connection == 'docker'
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_release == 'xenial'
  apt:
    update_cache: true

- name: establish dependencies
  apt:
    name: "{{ java_packages }}"
    state: present
  tags: install

- name: establish elasticsearch repo key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    id: D27D666CD88E42B4
    state: present
  tags: install

- name: establish elasticsearch repo
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ elk_version | int }}.x/apt stable main"
    state: present
    filename: elk
  tags: install
